local lexers = vis.lexers
local colors = {
	['base00'] = '#1c1c1c', -- bg
	['base0A'] = '#d0d0d0', -- fg 
	['base01'] = '#2f2e2d', -- soft black
	['base02'] = '#a36666', -- red
	['base03'] = '#90a57d', -- soft green
	['base04'] = '#d7af87', -- soft yellow
	['base05'] = '#7fa5bd', -- soft blue
	['base06'] = '#c79ec4', -- magenta
	['base07'] = '#8adbb4', -- green
	['base08'] = '#d0d0d0', -- white/grey
	['base09'] = '#4a4845', -- black/brown
	['base10'] = '#d78787', -- soft red
	['base11'] = '#afbea2', -- soft green
	['base12'] = '#e4c9af', -- white
	['base13'] = '#a1bdce', -- other blue
	['base14'] = '#d7beda', -- new magenta
	['base15'] = '#b1e7dd', -- ciano
	['base16'] = '#efefef', -- white.
}

lexers.colors = colors
local fg = ',fore:'..colors.base0A..','
local bg = ',back:'..colors.base00..','
--
lexers.STYLE_DEFAULT = bg..fg
lexers.STYLE_NOTHING = bg
lexers.STYLE_CLASS = 'fore:'..colors.base16
lexers.STYLE_COMMENT = 'fore:'..colors.base01
lexers.STYLE_CONSTANT = 'fore:'..colors.base05
lexers.STYLE_DEFINITION = 'fore:'..colors.base06
lexers.STYLE_ERROR = 'fore:'..colors.base10..',italics'
lexers.STYLE_FUNCTION = 'fore:'..colors.base01
lexers.STYLE_KEYWORD = 'fore:'..colors.base06
lexers.STYLE_LABEL = 'fore:'..colors.base04
lexers.STYLE_NUMBER = 'fore:'..colors.base04
lexers.STYLE_OPERATOR = 'fore:'..colors.base0A
lexers.STYLE_REGEX = 'fore:'..colors.base11
lexers.STYLE_STRING = 'fore:'..colors.base03
lexers.STYLE_PREPROCESSOR = 'fore:'..colors.base04
lexers.STYLE_TAG = 'fore:'..colors.base04
lexers.STYLE_TYPE = 'fore:'..colors.base14
lexers.STYLE_VARIABLE = 'fore:'..colors.base10..',bold'
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = 'back:'..colors.base05
lexers.STYLE_IDENTIFIER = 'fore:'..colors.base0A
lexers.STYLE_LINENUMBER = 'fore:'..colors.base09
lexers.STYLE_CURSOR = 'fore:'..colors.base01..',back:'..colors.base12
lexers.STYLE_CURSOR_PRIMARY = 'fore:'..colors.base01..',back:'..colors.base16
lexers.STYLE_CURSOR_LINE = 'back:'..colors.base09..',fore:'..colors.base0A
lexers.STYLE_SELECTION = 'fore:reverse'..colors.base12..',back:'..colors.base0A
lexers.STYLE_STATUS = 'back:'..colors.base01..',fore:'..colors.base09
lexers.STYLE_STATUS_FOCUSED = 'back:'..colors.base01..',fore:'..colors.base0A
lexers.STYLE_SEPARATOR = lexers.STYLE_DEFAULT
lexers.STYLE_INFO = 'fore:'..colors.base04..',back:default'
lexers.STYLE_EOF = ''
